name: qkp
description: QKP property app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sticky_headers: ^0.1.8
  nb_utils: ^3.3.0+1
  fluttertoast: ^7.1.6
  http: ^0.12.2
  pull_to_refresh: 1.6.3
  font_awesome_flutter: 8.12.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  marquee_widget: ^1.0.0
  countup: ^0.1.3
  adaptive_action_sheet: ^1.1.0
  syncfusion_flutter_charts: ^18.4.44+1
  modal_bottom_sheet: ^1.0.0+1
  dropdown_search: ^0.4.9
  searchable_dropdown: ^1.1.3
  flutter_svg: ^0.19.1
  camera: ^0.7.0+2
  image_picker: ^0.6.7+22
  carousel_slider: ^3.0.0
  photo_view: ^0.10.3
  foldable_sidebar: ^1.0.0
#  Google Map
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.1
  flutter_google_places: ^0.2.8
  google_maps_webservice: ^0.0.19
  google_api_headers: ^0.1.1+2
  flutter_html: ^1.2.0
#  dio: ^3.0.10
  local_auth: ^0.6.3+4
  image_cropper: ^1.3.1
  flutter_datetime_picker: ^1.5.0
  webview_flutter: ^1.0.7
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  firebase_database: ^4.4.0
  progress_dialog: ^1.2.4
  url_launcher: ^5.7.10
  flutter_sound: ^7.8.4
  path_provider: ^1.6.28
  permission_handler: ^5.1.0+2
  http_parser: ^3.1.4
  assets_audio_player: ^2.0.15
  flutter_downloader: ^1.5.2
  overlay_support: any
  provider: ^4.3.3
  get: ^3.26.0
  encrypt: ^4.1.0
  clipboard: ^0.1.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audios/
    - assets/images/intro/opxa0.png
    - assets/images/intro/opxa1.png
    - assets/images/intro/opxa2.png
    - assets/images/intro/opxa3.png
    - assets/images/intro/opxa4.png
    - assets/images/intro/opxa5.png
    - assets/images/intro/opxa6.png
    - assets/images/intro/opxa7.png
    - assets/images/intro/opxa8.png


    - assets/images/app_logo.gif
    - assets/images/settings.png
    - assets/images/no_internet.png
    - assets/images/splash_logo.gif
    - assets/images/login_bg.gif
    - assets/images/logo.png
    - assets/images/logo_menu_h.png
    - assets/images/empty_box.png
    - assets/images/profile.png
    - assets/images/bid.png
    - assets/images/buyer.png
    - assets/images/dollar.png
    - assets/images/file.png
    - assets/images/seller.png
    - assets/images/hammer.gif
    - assets/images/house_loading_placeholder.gif
    - assets/images/Buyer.svg
    - assets/images/dollar.svg
    - assets/images/file.svg
    - assets/images/Seller.svg
    - assets/images/timer.svg
    - assets/images/placeholder.jpeg
    - assets/images/circular_timer.png
    - assets/images/bgwallet.png
    - assets/images/map.png
    - assets/images/login_bg.jpeg
    - assets/images/AWTReport.svg
    - assets/images/Reports.svg
    - assets/images/MapReport.svg
    - assets/images/MarketPerformance.svg
    - assets/images/MarketWatch.svg
    - assets/images/Newsfeed.svg
    - assets/images/TransactionHistory.svg
    - assets/images/user.png
    - assets/images/email.png
    - assets/images/phone.png
    - assets/images/logout.svg
    - assets/images/image_placeholder.gif
    - assets/images/top-arrow.png
    - assets/images/home.png
    - assets/images/home_white.png
    - assets/images/wallet.png
    - assets/images/watchfile.png
    - assets/images/fileIcon.png
    - assets/images/avatar.png
    - assets/images/propertyhome.png
    - assets/images/next.png
    - assets/images/pencil.png
    - assets/images/attachment.png
    - assets/images/msg.png
    - assets/images/microphone.png
    - assets/images/dots.png
    - assets/images/hemmar6.gif
    - assets/images/loading2.gif
    - assets/images/loading_circules.gif
    - assets/images/bell.png
    - assets/images/noti_file.png
    - assets/images/emojis/angry.png
    - assets/images/emojis/cool.png
    - assets/images/emojis/crying.png
    - assets/images/emojis/Happy.png
    - assets/images/emojis/smile.png
    - assets/images/mjcoders2.png

      # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Chango
      fonts:
        - asset: assets/fonts/Chango/Chango-Regular.ttf
    - family: Londrina_Solid
      fonts:
        - asset: assets/fonts/Londrina_Solid/LondrinaSolid-Black.ttf
        - asset: assets/fonts/Londrina_Solid/LondrinaSolid-Light.ttf
        - asset: assets/fonts/Londrina_Solid/LondrinaSolid-Regular.ttf
        - asset: assets/fonts/Londrina_Solid/LondrinaSolid-Thin.ttf
    - family: Poppins
      fonts:
        - asset:  assets/fonts/Poppins/Poppins-Black.ttf
        - asset:  assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset:  assets/fonts/Poppins/Poppins-Bold.ttf
        - asset:  assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset:  assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset:  assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset:  assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset:  assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset:  assets/fonts/Poppins/Poppins-Light.ttf
        - asset:  assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset:  assets/fonts/Poppins/Poppins-italic.ttf
        - asset:  assets/fonts/Poppins/Poppins-Medium.ttf
        - asset:  assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset:  assets/fonts/Poppins/Poppins-Regular.ttf
        - asset:  assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset:  assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset:  assets/fonts/Poppins/Poppins-Thin.ttf
        - asset:  assets/fonts/Poppins/Poppins-ThinItalic.ttf

      #  - asset: fonts/Schyler-Italic.ttf
      #    style: italic
#     - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
